### ISSUE TITLE
complete the best practices session draft

### ISSUE THREAD

**Issue by pearsonca** [pearsonca/stdio-ghana#12]
content in

https://github.com/pearsonca/stdio-ghana/tree/gh-pages/sessions/2014/bestpractices

**Comment by pearsonca** [comment]
@tjhladish on back up

**Comment by pearsonca** [comment]
A few incomplete thoughts:
- there are a couple of big principles that drive the practices you describe; those are things we want to stick, so may want to emphasize that upfront and call back to it throughout
  - need to communicate with other coders (on a development team, one's future self, maintainer)
  - write the least amount of code possible (YAGNI, DRY, etc)
- the focus on maintenance is less generally less relevant to scientific applications, though the issues of code comprehensibility to others remain
- some more detailed concepts aren't going to stick (Demeter, open / closed), but the basic ideas need to have practical examples
- need more incremental practical steps moving towards kicker assignment

Minor notes
- indentation style choices still matter in Python, despite indentation being a core syntactic component
- no KISS?  i.e., don't prematurely optimize
- there's tension between the YAGNI and defensive coding principles
- there is a naming format discussion, but no naming content discussion (e.g., name functions and parameters sensibly)

**Comment by arkerpay** [comment]
Carl,

Thanks for the review.  Agree that core principals need to be emphasized
and reinforced in the exercise.  What I wrote was a draft that can be
further developed into a solid lesson.  Looking forward to making
improvements.

I also recognize that what is presented are just good practices - their use
is subjective.  Using cutsey acronyms as if they were natural law has
always irritated me. I recall getting into a bitter debate over YAGNI with
a supervisor for the reason you mention.  There are times that you might
want to build more than you need at present because the portion of the code
is fresh in your mind and you can predict that the customer and BA did not
identify something obvious that they will need later.  There are times you
DO want to repeat yourself to keep the code readable or don't want to
over-generalize a function.  I can bring that up in the lesson.

I believe simplicity is important, but dislike the term KISS.  You can't
use it as a critique without implicitly calling someone stupid.  So I will
cover simplicity and mention that there is an acronym but I won't use it.

Disagree on maintenance in scientific applications. Source code should be a
deliverable for research grants and contracts and should be in a state
where it can be easily understood, extended and corrected for defects.  I
have been the recipient of good and bad research source code and really
appreciated the times where good practices were followed in its development.

Jonathon

**Comment by arkerpay** [comment]
How do you upload a file?  I see how I can create a text file.  What I want
is to upload graphics.

**Comment by pearsonca** [comment]
When you're viewing the file structure in the web interface, there's a little [+] beside the path near the top of the page.  In a local copy, it's just like any other fs interaction, but make sure to sync the addition afterwards.

**Comment by arkerpay** [comment]
Doesn't work.  It wants me to name a file and then type stuff.  I want to
upload a graphic image.

**Comment by pearsonca** [comment]
Agree re KISS label - I prefer Knuth's framing re premature optimization, but its not quite as general.

On the maintenance perspective, let me clarify: I'm making a point about the surrounding context - my experience with scientific code is that it is more often short-lived / one-off (not just because its often unmaintainable).  You're totally correct that scientists frequently handover code that has no comprehensible content, and that is bad - but I think the more important perspective is that this makes peer review impossible, not that it makes maintenance impossible.

Fortunately, one important (pedagogical) part of the course is that instructors have different, valid opinions about concepts.  This is something they're rarely taught, but is critical to being able to handle the real world (in all sorts of ways).

**Comment by arkerpay** [comment]
Different valid opinions about concepts?  Wait until they get a load of the
software requirements lesson I am working on right now!  We're talking holy
wars.

**Comment by pearsonca** [comment]
Hrm, right you are re upload.  If it is available via the web interface, I'm sure a bit of Googling will locate it.  Otherwise, you may have to finally learn about using git the commandline / gui tool.

**Comment by pearsonca** [comment]
Another thought at the draft level: we might want to think about the complementary perspective, aka ``code smell'' / worst practices.

It's sort of implicit in the kicker exercise, but we may want to highlight identifying less-than-perfect code.

Pedagogically / practically, it's often a two-step process anyway: see what's wrong, then adjust.

**Comment by pearsonca** [comment]
Shifting into a polish issue; will link this one in the description
